name: Deploy to Vercel

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git safe directory
        run: |
          git config --global --unset-all safe.directory
          git config --global --add safe.directory /home/runner/work/E-Learning

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Change working directory
        run: cd /home/runner/work/E-Learning

      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.E_Learning_Vercel_Token }} --prod client
