name: Netlify Deploy

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'E-Learning/client'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Export Next.js app
        run: npm run export

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: ./out
          deploy-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          flags: --prod
