name: Deploy to Vercel

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: |
            cd client
            npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to Vercel
        uses: vercel-action@v21
        with:
          github-token: ${{ secrets.MY_PAT }}
